apiVersion: apps/v1
kind: Deployment
metadata:
  name: prince-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prince-bot
  template:
    metadata:
      name: prince-bot
      labels:
        app: prince-bot
    spec:
      containers:
      - name: prince-bot
        image: adnan10101/troll-bot:0.0.5
